name: cms

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  cms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' # Specify the Python version you need
    
      - name: Run apt and pip
        run: |
          sudo apt update
          sudo apt install p7zip-full
          sudo apt install curl
          pip install requests
          pip install pytz
          pip install python-telegram-bot
          pip install PyGithub

      - name: Run Python script
        run: |
          python cms.py
        env:
            github_token: ${{ secrets.PAT_GITHUB }}
            bot_token: ${{ secrets.BOT_TOKEN }}
            chat_id: ${{ secrets.CHAT_ID_COVER }}

