name: cms_certain

on:
  workflow_dispatch:

jobs:
  cms_certain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Specify the Python version you need
    
      - name: Run apt and pip
        run: |
          sudo apt update
          pip install requests
          pip install bs4
          pip install lxml

      - name: Run Python script
        run: |
          python lemino_cms.py
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID_BOT_CHANNEL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
